//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyBotApp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TableData
    {
        public int Id { get; set; }
        public string UserID { get; set; }
        public string UserName { get; set; }
        public string Channel { get; set; }
        public System.DateTime created { get; set; }
        public string Message { get; set; }
        public string BeSymbol { get; set; }
        public string BeName { get; set; }
        public Nullable<double> BeValue { get; set; }
    }
}
